services:
  nginx:
    image: nginx:latest
    container_name: transcendence_nginx
    ports:
      - "4043:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - backend
      - frontend
    networks:
      - transcendence_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - secrets/.env
    command: [ "node", "--inspect=0.0.0.0:9229", "server.js" ]
    ports:
      - "9229:9229"
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - transcendence_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: transcendence_frontend
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - backend
    networks:
      - transcendence_network

  prometheus:
    image: prom/prometheus:latest
    container_name: transcendence_prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./devops/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./devops/prometheus/alerts.yml:/etc/prometheus/alerts.yml
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.retention.time=30d'
      - '--storage.tsdb.path=/prometheus'
      - '--web.enable-lifecycle'
    restart: unless-stopped
    networks:
      - transcendence_network

  grafana:
    image: grafana/grafana:latest
    container_name: transcendence_grafana
    ports:
      - "3000:3000"
    volumes:
      - ./devops/grafana/provisioning/:/etc/grafana/provisioning/
      - ./devops/grafana/dashboards:/var/lib/grafana/dashboards
      - grafana-data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER__FILE=/run/secrets/grafana_user
      - GF_SECURITY_ADMIN_PASSWORD__FILE=/run/secrets/grafana_password
      - GF_USERS_ALLOW_SIGN_UP=false
    secrets:
      - grafana_user
      - grafana_password
    restart: unless-stopped
    networks:
      - transcendence_network

  node_exporter:
    image: prom/node-exporter:latest
    container_name: transcendence_node_exporter
    ports:
      - "9100:9100"
    volumes:
      - db-metrics:/var/lib/node_exporter/textfile_collector
    command:
      - '--collector.textfile.directory=/var/lib/node_exporter/textfile_collector'
    restart: unless-stopped
    networks:
      - transcendence_network

volumes:
  prometheus-data:
  grafana-data:
  db-metrics:

secrets:
  backend_env:
    file: secrets/.env
  grafana_user:
    file: secrets/GFuser
  grafana_password:
    file: secrets/GFpass

networks:
  transcendence_network:
    driver: bridge